services:
  db-dev:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_dev_data:/var/lib/postgresql/data

  api-dev:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    image: smrt-api-dev
    ports:
      - "${API_PORT}:${INTERNAL_PORT}"
    networks:
      default:
        aliases:
          - api
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db-dev:5432/${DB_NAME}?schema=public"
      PORT: ${INTERNAL_PORT}
      CORS_ORIGIN: ${CORS_ORIGIN}
    depends_on:
      - db-dev

  web-dev:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    image: smrt-web-dev
    ports:
      - "${WEB_PORT}:80"
    environment:
      VITE_API_URL: ${API_URL}
    depends_on:
      - api-dev
    volumes:
      - ./logs/nginx-dev:/var/log/nginx

volumes:
  db_dev_data: