name: smrt-prod

services:
  smrt-db-prod:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${EXTERNAL_DB_PORT}:${INTERNAL_DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  smrt-api-prod:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    image: smrt-api-prod
    ports:
      - "${PORT}:${INTERNAL_PORT}"
    env_file: .env.prod
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${INTERNAL_DB_PORT}/${DB_NAME}?schema=public"
      LOG_LEVEL: ${LOG_LEVEL}
      CORS_ORIGIN: ${CORS_ORIGIN}
      COOKIE_SECRET: ${COOKIE_SECRET}
      PORT: ${INTERNAL_PORT}
      HOST: ${HOST}
      CLI_URL: ${CLI_URL}
      AUTO_MIGRATE: "true"
    depends_on:
      - smrt-db-prod

  smrt-web-prod:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    image: smrt-web-prod
    ports:
      - "${WEB_PORT}:${INTERNAL_WEB_PORT}"
    environment:
      API_PROXY_URL: ${API_PROXY_URL}
    depends_on:
      - smrt-api-prod
    volumes:
      - ./logs/nginx:/var/log/nginx

volumes:
  db_data: