name: smrt-test

services:
  smrt-db-test:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${EXTERNAL_DB_PORT}:${INTERNAL_DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    # No volumes here = ephemeral data

  smrt-api-test:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    image: smrt-api-test
    ports:
      - "${API_PORT}:${INTERNAL_PORT}"
    env_file: .env.test
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${INTERNAL_DB_PORT}/${DB_NAME}?schema=public"
      LOG_LEVEL: ${LOG_LEVEL}
      CORS_ORIGIN: ${CORS_ORIGIN}
      COOKIE_SECRET: ${COOKIE_SECRET}
      PORT: ${INTERNAL_PORT}
      HOST: ${HOST}
      CLI_URL: ${CLI_URL}
      AUTO_MIGRATE: "true"
    depends_on:
      - smrt-db-test

  smrt-web-test:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    image: smrt-web-test
    ports:
      - "${WEB_PORT}:${INTERNAL_WEB_PORT}"
    environment:
      VITE_API_URL: ${API_URL}
      API_PROXY_URL: ${API_PROXY_URL}
    depends_on:
      - smrt-api-test
    volumes:
      - ./logs/nginx-test:/var/log/nginx
